import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
import {parseHTML} from 'linkedom';
import {StudioGesture,firstMissingBrief} from '../assets/spatial-controls.js';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixture.json',import.meta.url),'utf8'));
async function run(width){
 const {document,window}=parseHTML(fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'));let active=null;Object.defineProperty(document,'activeElement',{get:()=>active});document.fonts={ready:Promise.resolve()};
 Object.defineProperty(window.HTMLInputElement.prototype,'checked',{configurable:true,get(){return this.hasAttribute('checked')},set(v){if(v)this.setAttribute('checked','');else this.removeAttribute('checked')}});
 window.HTMLElement.prototype.focus=function(){active=this;};window.HTMLElement.prototype.getBoundingClientRect=function(){if(this.id==='scene-guide')return {top:620,left:22,right:width-22,bottom:760};if(this.classList.contains('header'))return {top:0,bottom:64};if(this.classList.contains('panel'))return {left:38,right:403,top:150,bottom:740};return {top:0,bottom:0,left:0,right:0};};
 for(const el of document.querySelectorAll('dialog')){Object.defineProperty(el,'open',{get:()=>el.hasAttribute('open')});el.showModal=()=>el.setAttribute('open','');el.close=()=>{el.removeAttribute('open');el.dispatchEvent(new window.Event('close'));};}
 const audio=document.querySelector('audio');audio.paused=true;audio.play=async()=>{audio.paused=false;audio.onplay?.();};audio.pause=()=>{audio.paused=true;audio.onpause?.();};
 class FakeStudio{constructor(){this.light=false;this.anchors=[];this.frames=[];globalStudio=this;}setTracks(){}setProducts(p){this.products=p;}setScreen(){}setInfo(){}setHotspots(){}move(v){this.zone=v;}frame(...r){this.frames.push(r);}focusProduct(i,zoom){this.index=i;this.zoom=zoom;}tone(){}pulse(){}setPlaying(){}connectAudio(){}lookAround(){}zoomBy(){}resetView(){}nudge(){}pick(){return null;}hover(){return false;}setLight(v){this.light=v;}}
 let globalStudio;const requests=[],raf=[];const sandbox={document,window,console,crypto:webcrypto,Intl,URLSearchParams,FormData,innerWidth:width,innerHeight:844,navigator:{},sessionStorage:{getItem(){return null},setItem(){}},location:{search:'',hash:'',pathname:'/',protocol:'http:'},history:{replaceState(){}},requestAnimationFrame:f=>raf.push(f),addEventListener(){},setInterval(){},setTimeout(){return 1;},clearTimeout(){},ResizeObserver:class{observe(){}disconnect(){}},fetch:async(url,options)=>{requests.push({url,options});return {ok:true,json:async()=>url.includes('my-orders')?{orders:[]}:fixture};},Studio:FakeStudio,StudioGesture,firstMissingBrief,MOODS:{Romántica:0xff7788}};
 const code=fs.readFileSync(new URL('../assets/app.js',import.meta.url),'utf8').replace(/^import .*\n/gm,'')+'\nglobalThis.inspect={go,studioAction,render,openOptions,closeOptions,frameStudio,getView:()=>view,getDraft:()=>draft};';vm.createContext(sandbox);vm.runInContext(code,sandbox);await new Promise(setImmediate);await new Promise(setImmediate);
 const q=s=>document.querySelector(s),api=sandbox.inspect;assert.equal(api.getView(),'lobby');assert.equal(q('#content').parentElement.id,'mobile-content');assert.ok(!q('#options-dialog').open);api.frameStudio();assert.equal(globalStudio.frames.at(-1)[3],844-(width<760?205:150));
 // Browse the packages before giving personal information.
 api.go('products');assert.equal(api.getView(),'products');assert.equal(globalStudio.zoom,width<760);
 if(width<760){assert.equal(document.querySelectorAll('.product-card').length,1);q('[data-package-next]').click();assert.equal(globalStudio.index,2);q('[data-open-options]').click();assert.ok(q('#options-dialog').open);assert.equal(api.getDraft().product,'full');assert.ok(q('.product-details').hasAttribute('open'));assert.match(q('.product-card').textContent,/Video emocional/);q('#next').click();assert.equal(api.getView(),'genre');assert.ok(!q('#options-dialog').open);q('[data-open-options]').click();assert.ok(q('#options-dialog').open);}else assert.equal(document.querySelectorAll('.product-card').length,3);
 // Real delegated click/input handlers drive the creation flow.
 api.go('genre');api.openOptions();q('[data-pick="genre"]').click();assert.ok(api.getDraft().genre);q('#next').click();assert.equal(api.getView(),'mood');api.openOptions();q('[data-pick="mood"]').click();q('#next').click();assert.equal(api.getView(),'voice');api.openOptions();q('[data-pick="voice"]').click();q('#next').click();assert.equal(api.getView(),'story');api.openOptions();
 for(const [name,value] of Object.entries({recipient:'Luna',occasion:'Aniversario',story:'Recordamos aquel viaje a la playa que nos cambió la vida.'})){const input=q(`[name="${name}"]`);input.value=value;input.dispatchEvent(new window.Event('input',{bubbles:true}));}
 q('#next').click();assert.equal(api.getView(),'products');api.openOptions();q('#next').click();assert.equal(api.getView(),'checkout');if(width<760)assert.ok(q('#options-dialog').open);
 // A legal round trip retains the entire draft and reopens the checkout dialog.
 const recipient=api.getDraft().recipient;q('[name="consent"]').checked=true;q('[name="consent"]').dispatchEvent(new window.Event('change',{bubbles:true}));q('[data-go="terms"]').click();assert.equal(api.getView(),'terms');q('.panel [data-go="checkout"]').click();assert.equal(api.getView(),'checkout');assert.equal(api.getDraft().recipient,recipient);assert.ok(q('[name="consent"]').checked);if(width<760){assert.ok(q('#options-dialog').open);q('#close-options').click();assert.ok(!q('#options-dialog').open);}
 // A scene object opens the editor even if this is already the active station.
 api.studioAction({action:{type:'go',view:'voice'}});assert.equal(api.getView(),'voice');if(width<760)assert.ok(q('#options-dialog').open);
 assert.ok(requests.every(r=>!r.options.body),'No order, payment or email write in UI tests');
 console.log(`PASS ${width}px: real DOM event flow, modal mount/open/close, package browsing, selections, text input, legal return and consent retention.`);
}
await run(390);await run(1440);
